#!/usr/bin/env bash
# client_config.sh — generates portable inline .ovpn client profiles.

if [ -n "${_OVPN_CLICFG_LOADED:-}" ]; then return 0 2>/dev/null || exit 0; fi
_OVPN_CLICFG_LOADED=1

# ccfg_remote_lines: one "remote host port proto" line per configured
# listener, in configured order — OpenVPN Connect / the CLI client try them
# in order and fail over automatically, which is what gives dual/multi-mode
# profiles their transport fallback behavior.
_ccfg_remote_lines() {
	local host="$1" entry proto port
	IFS=',' read -ra _entries <<<"$(state_get LISTENERS "")"
	for entry in "${_entries[@]}"; do
		[ -n "$entry" ] || continue
		IFS='|' read -r _ proto port _ _ <<<"$entry"
		echo "remote ${host} ${port} ${proto}"
	done
}

# ccfg_export name output_path
ccfg_export() {
	local name="$1" outfile="$2"
	valid_client_name "$name" || die "Invalid client name: '$name'"
	[ -f "${PKI_DIR}/issued/${name}.crt" ] || die "No such client: '${name}'. Use 'ovpn client add ${name}' first."
	[ -f "${PKI_DIR}/private/${name}.key" ] || die "Private key for '${name}' not found."

	local status
	status="$(pki_client_status "$name" 2>/dev/null || echo unknown)"
	[ "$status" = "revoked" ] && die "Client '${name}' is revoked; cannot export a usable profile."

	local host
	host="$(state_get PUBLIC_HOST)"
	[ -n "$host" ] || die "PUBLIC_HOST is not set in state; run 'ovpn settings' first."

	ensure_dir "$(dirname "$outfile")" 0700

	local remote_count
	remote_count="$(_ccfg_remote_lines "$host" | wc -l | tr -d ' ')"

	local tmp; tmp="$(mktemp)"
	{
		echo "# OpenVPN client profile for '${name}'"
		echo "# Generated by OpenVPN Server Manager v${MANAGER_VERSION}"
		echo "client"
		echo "dev tun"
		_ccfg_remote_lines "$host"
		if [ "$remote_count" -gt 1 ]; then
			# Fail over to the next 'remote' quickly instead of OpenVPN's
			# 120s default, so dual/multi-listener profiles actually behave
			# like a primary/fallback pair rather than a very slow retry.
			echo "connect-timeout 10"
		fi
		echo "resolv-retry infinite"
		echo "nobind"
		echo "persist-key"
		echo "persist-tun"
		echo "remote-cert-tls server"
		echo "data-ciphers ${DEFAULT_DATA_CIPHERS}"
		echo "data-ciphers-fallback ${DEFAULT_FALLBACK_CIPHER}"
		echo "auth ${DEFAULT_AUTH_DIGEST}"
		echo "tls-version-min ${DEFAULT_TLS_VERSION_MIN}"
		echo "verb 3"
		echo "mute 20"
		echo
		echo "<ca>"
		cat "${PKI_DIR}/ca.crt"
		echo "</ca>"
		echo "<cert>"
		openssl x509 -in "${PKI_DIR}/issued/${name}.crt"
		echo "</cert>"
		echo "<key>"
		cat "${PKI_DIR}/private/${name}.key"
		echo "</key>"
		echo "<tls-crypt>"
		cat "${PKI_DIR}/tls-crypt.key"
		echo "</tls-crypt>"
	} >"$tmp"

	install -o root -g root -m 0600 "$tmp" "$outfile"
	rm -f "$tmp"
	log_ok "Exported client profile: ${outfile}"
}

ccfg_default_path() {
	local name="$1"
	printf '%s/%s.ovpn\n' "$CLIENT_EXPORT_DIR" "$name"
}
